### ISSUE TITLE
Does this need to be a Wordpress plugin?

### ISSUE THREAD

**Issue by chrisgherbert** [WebDevStudios/CPT_Core#17]
I'd like to use this as a dependency in a theme and manage it using Composer.  Unfortunately, because its composer.json type is `wordpress-plugin` it installs into a `wp-content/plugins` subdirectory of the theme, which of course doesn't work.

Overriding this by setting `installer-paths` back to `vendor` for cpt-core in my theme's `composer.json` works fine but it feels kind of gross.

Have you considered making this a standard Composer library?  It doesn't seem like it really needs to be a Wordpress plugin, necessarily.

**Comment by JayWood** [comment]
@chrisgherbert This can be used as a WordPress plugin, in fact that was it's original intention. It sounds like your composer.json is customized beyond what we normally do, would you mind sharing it?

**Comment by JayWood** [comment]
no response in quite some time, closing.

**Comment by ethanclevenger91** [comment]
I'd like to re-open this. Shouldn't be defined as such. It doesn't have a WP plugin definition file, and as such, doesn't belong in wp-content (which is where it gets put). Seems it should either be bundled with plugins/themes that require it, or when used in a Bedrock-like setup, should be required via Composer and loaded via the Composer autoloader
