### ISSUE TITLE
Add support for custom installation path via Composer

### ISSUE THREAD

**Issue by grantpalin** [WebDevStudios/CPT_Core#9]
While this code can be installed via the Composer as source, the current composer.json doesn't allow for custom installation paths. I've been able to make this happen with CMB2 which does have the appropriate composer.json configuration.

Since I'd like to use this source as part of a plugin, it would be convenient t be able to consume it through Composer.

**Comment by CamdenSegal** [comment]
I've updated the composer.json file to support installing CPT_Core as a WordPress plugin 9c08de22a4c06b29dbb719707913f28d8a3b1710.

In addition as a package consumer you are able to manually specify where each package is installed using composer/installers installer-paths https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by grantpalin** [comment]
Thanks for the change. That is much what I was thinking of, to be able to manage dependencies as part of a plugin. Given the change, I've been able to direct Composer to put the helper library in a includes folder.
